# ---Translator---
apiKey: <put your apikey here>
subscriptionRegion: <put the subscription region here>

# ---Discord---
discordEnabled: false
status: Minecraft
botToken: <put the bot token here>
guildId: <put the id of the guild here>
channelId: <put the id of the channel here>
staffChannelId: <put the id of the channel here>
donorChannelId: <put the id of the channel here>
webhook: <put the webhook here>
staffWebhook: <put the webhook here>
donorWebhook: <put the webhook here>

# Configure which roles can use color codes with Discord -> Minecraft
# For example:
#
# colorCodeRoles: [1234567891234567890, 0987654321987654321]

# Configure the text color (after the username (Discord -> Minecraft)) for certain roles
# For example:
#
# roles:
#     1234567891234567890:
#         message_color: RED
#
# message_color can be one of these: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
#
# You can also use RGB as the color:
#
# roles:
#     1234567891234567890:
#         message_color: [255, 255, 255]
