name: Chat-OG
version: '${version}'
main: nl.skbotnl.chatog.ChatOG
author: SKBotNL
api-version: 1.18
depend: [PlaceholderAPI, Vault]
commands:
  translatemessage:
    description: translatemessage
    usage: /translatemessage <uuid> <iscustommessage>
  translatesettings:
    description: translatesettings
    usage: /translatesettings <language>
  chatconfigreload:
    description: chatconfigreload
    usage: /chatconfigreload