name: Chat-OG
version: '${version}'
main: nl.skbotnl.chatog.ChatOG
author: SKBotNL
api-version: '${apiVersion}'
depend: [ PlaceholderAPI, Vault, AnnouncerPlus, Utilities-OG, Essentials ]
commands:
  translatemessage:
    description: Internal command for translating messages
    usage: /translatemessage <uuid> <messagetype>
  translatesettings:
    description: Change which language you want the translator to translate to
    usage: /translatesettings <language>
  chatconfigreload:
    description: Reload Chat-OG's config
    usage: /chatconfigreload
  sc:
    description: Toggle or talk in staff chat
    usage: /sc OR /sc <message here>
  s:
    description: Toggle or talk in staff chat
    usage: /s OR /s <message here>
  p:
    description: Toggle or talk in premium chat
    usage: /p OR /p <message here>
