name: Chat-OG
version: '${version}'
main: nl.skbotnl.chatog.ChatOG
author: SKBotNL
api-version: 1.18
depend: [PlaceholderAPI, Vault]
commands:
  translatemessage:
    description: Internal command for translating messages
    usage: /translatemessage <uuid> <iscustommessage>
  translatesettings:
    description: Change which language you want the translator to translate to
    usage: /translatesettings <language>
  chatconfigreload:
    description: Reload Chat-OG's config
    usage: /chatconfigreload
  sc:
    description: Toggle or talk in staff chat
    usage: /sc OR /sc <message here>
  s:
    description: Toggle or talk in staff chat
    usage: /s OR /s <message here>
  dc:
    description: Toggle or talk in donor chat
    usage: /dc OR /dc <message here>
  d:
    description: Toggle or talk in donor chat
    usage: /d OR /d <message here>